services:
  user:
    container_name: ddd-user
    build: ../
    restart: on-failure
    environment:
      - APP_ENV=dev
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      go-ddd-example:
    volumes:
      - ./../tmp:/app/tmp

  db:
    image: postgres:16-alpine
    container_name: ddd-user_db
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5435:5432
    volumes:
      - ddd-user_db_volume:/var/lib/postgresql/data
    networks:
      go-ddd-example:

networks:
  go-ddd-example:

volumes:
  ddd-user_db_volume:
