services:
  db:
    image: postgres:16-alpine
    container_name: ddd-user_db
    restart: on-failure
    env_file:
        - ./../config/dev.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5435:5432
    volumes:
      - ddd-user_db_volume:/var/lib/postgresql/data

volumes:
  ddd-user_db_volume:
